export const CANVAS_WIDTH = 3840;
export const CANVAS_HEIGHT = 2420;
export const ASPECT_RATIO = CANVAS_WIDTH / CANVAS_HEIGHT;
export const EXPORT_WIDTH = 3840;
export const EXPORT_HEIGHT = 2420;
export const MANIFEST_URL = '/manifest.json';
export const THUMB_WIDTH = 240;
export const EXPORT_FILENAME = 'id-card';
export const TEXT_INK = '#4a2c3a'; // keep in sync with $ink in _settings.scss
